In [120]:
import numpy as np

# 4 ways of Dot product

In [121]:
m1 = np.arange(9).reshape(3, 3)
m2 = np.arange(9).reshape(3, 3)

# way1 :
print(np.matmul(m1, m2))
print()
# way2:
print(np.dot(m1, m2))
print()
# way3:
print(m1@m2)
print()
# way4:
print(m1.dot(m2))


[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]

[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]

[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]

[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]


# reshape(-1,1)


The reshape(-1, 1) operation reshapes the array into a 2-dimensional array with a single column.
The -1 value acts as a placeholder for the number of rows, allowing NumPy to automatically calculate it based on the array's size.
It is commonly used to convert a 1-dimensional array into a column vector.

In [122]:
# 1D array
ar = np.arange(10).reshape(-1,1)
print(ar)

# 2D array
ar = np.arange(12).reshape(4,3)
print(ar.reshape(1,-1))

# 3D array
ar = np.arange(8).reshape(2,2,2)
print(ar.reshape(-1,1))

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


# copy() function

In [123]:
m = np.arange(3)
print(m)
# assigning n = m creates another reference to the same array, and modifying n affects m as well.
n = m
n[0] = 10
print(m)

# copy creates another copy of given matrix changes made on one wont reflect in another.
a = np.copy(m)
a[0] = 50
print("a", a)
print("m", m)


[0 1 2]
[10  1  2]
a [50  1  2]
m [10  1  2]


# view()

The view() method in NumPy creates a new array object that views the same data as the original array but with a different shape or data type. It does not create a copy of the data but rather provides a different "view" or interpretation of the original data.

In [124]:
a1 = np.arange(9).reshape(3, 3)

# changing dimension and datatype of array without creating a copy
view_a1 = a1.view(np.int16).reshape(6, 3)

# changes made reflects to a1 also
view_a1[0, 0] = 5

print(f"a1: \ndim : {a1.ndim} , dtype : {a1.dtype}")
print(a1)

print(f"\nview: \ndim : {view_a1.ndim} , dtype : {view_a1.dtype}")
print(view_a1)


a1: 
dim : 2 , dtype : int32
[[5 1 2]
 [3 4 5]
 [6 7 8]]

view: 
dim : 2 , dtype : int16
[[5 0 1]
 [0 2 0]
 [3 0 4]
 [0 5 0]
 [6 0 7]
 [0 8 0]]


# Broadcasting

In [125]:
a1 = np.arange(3).reshape(1, 3)
a2 = np.arange(4).reshape(4, 1)

print(a1)
print(a2)
print(a1 + a2)  # shape would be 4*3
print(a1 * a2)  # shape would be 4*3
print(5*a1)
print(10+a1)


[[0 1 2]]
[[0]
 [1]
 [2]
 [3]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]
[[0 0 0]
 [0 1 2]
 [0 2 4]
 [0 3 6]]
[[ 0  5 10]]
[[10 11 12]]


In [126]:
a = np.arange(12).reshape(4, 3)
b = np.arange(3)

print(a)
print(b)

print(a+b)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [127]:
a = np.arange(12).reshape(3, 4)
b = np.arange(3)

print(a)
print(b)

print(a+b)  # diffrent shapes throws error
# operands could not be broadcast together with shapes (3,4) (4,3)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [ ]:
a = np.arange(12).reshape(3, 4)
b = np.arange(12).reshape(4, 3)

print(a)
print(b)

print(a+b)  # diffrent shapes throws error
# operands could not be broadcast together with shapes (3,4) (4,3)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 